name: image_les_than_image
description: "PNGpng - 画像圧縮PCソフト"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.4.0
  process_run: ^0.12.2
  path: ^1.8.3
  glassmorphism: ^2.0.0
  image: ^4.0.17
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

